# Generated by Django 3.2.5 on 2021-07-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerGuide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
