# Generated by Django 3.2.5 on 2021-07-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerGuide', '0003_auto_20210713_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='flowerSlug',
        ),
        migrations.AddField(
            model_name='flower',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
