# Generated by Django 3.2.5 on 2021-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerGuide', '0004_auto_20210713_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
