# Generated by Django 3.2.5 on 2021-07-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerGuide', '0006_auto_20210713_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='slug',
        ),
        migrations.DeleteModel(
            name='FlowerImage',
        ),
    ]
