# Generated by Django 3.2.5 on 2021-07-14 17:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerGuide', '0007_auto_20210714_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
