# Generated by Django 3.2.5 on 2021-07-14 17:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerGuide', '0008_flower_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
